apiVersion: v1
kind: ConfigMap
metadata:
  name: book-service-config
  namespace: default
data:
  application.yml: |
    book:
      database:
        url: jdbc:sqlite:/application/data/book-info.db
    server:
      port: 8080

