book:
  database:
    url: jdbc:sqlite:data/book-info.db
server:
  port: 9095
#spring:
#  jackson:
#    default-property-inclusion: non_null
#spring:
#  jackson:
#    default-property-inclusion: non_null