apiVersion: v1
kind: Pod
metadata:
  name: book-details-service
  labels:
    app: book-details-service
    env: dev
spec:
  containers:
  - name: book-details-service
    image: rnkoaa/book-details-service:latest
    ports:
    - containerPort: 8080
    # livenessProbe:
    #   httpGet:
    #     path: /actuator/health
    #     port: 8080
    #     initialDelaySeconds: 5
    #     periodSeconds: 60
    volumeMounts:
    - name: book-details-service-config-volume
      mountPath: /application/config/application.yml
      subPath: application.yml
  volumes:
    - name: book-details-service-config-volume
      configMap: 
        name: book-details-service-config


