apiVersion: v1
kind: ConfigMap
metadata:
  name: book-details-service-config
  namespace: default
data:
  application.yml: |
    server:
      port: 8080
    review:
      info:
        url: http://review-service:8080/
    book:
      info:
        url: http://book-service:8080/
