---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: book-service-account
---
# config-map
apiVersion: v1
kind: ConfigMap
metadata:
  name: book-service-config
  namespace: default
data:
  application.yml: |
    book:
      database:
        url: jdbc:sqlite:/application/data/book-info.db
    server:
      port: 8080

# pod
---
apiVersion: v1
kind: Pod
metadata:
  name: book-service
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
  labels:
    app: book-service
    env: dev
spec:
  serviceAccountName: book-service-account
  containers:
  - name: book-service
    image: rnkoaa/book-service:latest
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: book-service-config-volume
      mountPath: /application/config/application.yml
      subPath: application.yml
    - name: db-data
      mountPath: /application/data
  initContainers:
    - name: init-book-pod
      image: busybox:1.28
      command:
        - wget
        - "--no-check-certificate"
        - "-O"
        - "/application/data/book-info.db"
        - "https://raw.githubusercontent.com/rnkoaa/book-info/master/data/book-info.db"
      volumeMounts:
        - mountPath: /application/data
          name: db-data
  volumes:
    - name: book-service-config-volume
      configMap: 
        name: book-service-config
    - emptyDir: {}
      name: db-data

# ---
# deployment
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: book-service-deployment
#   annotations:
#     "consul.hashicorp.com/connect-inject": "true"
#   labels:
#     app: book-service
#     env: dev
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: book-service
#       env: dev
#   template:
#     metadata:
#       labels:
#         app: book-service
#         env: dev
#     spec:
#       serviceAccountName: book-service-account
#       initContainers:
#       - name: init-book-pod
#         image: busybox:1.28
#         command:
#           - wget
#           - "--no-check-certificate"
#           - "-O"
#           - "/application/data/book-info.db"
#           - "https://raw.githubusercontent.com/rnkoaa/book-info/master/data/book-info.db"
#         volumeMounts:
#           - mountPath: /application/data
#             name: db-data
#       containers:
#       - name: book-service
#         image: rnkoaa/book-service:latest
#         ports:
#         - containerPort: 8080
#         volumeMounts:
#         - name: book-service-config-volume
#           mountPath: /application/config/application.yml
#           subPath: application.yml
#         - name: db-data
#           mountPath: /application/data
#       volumes:
#         - name: book-service-config-volume
#           configMap: 
#             name: book-service-config
#         - emptyDir: {}
#           name: db-data