---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: book-details-service-account

---
# config-map
apiVersion: v1
kind: ConfigMap
metadata:
  name: book-details-service-config
  namespace: default
data:
  application.yml: |
    server:
      port: 8080
    review:
      info:
        url: http://localhost:9095/
    book:
      info:
        url: http://localhost:9090/

---
apiVersion: v1                # API version
kind: Service                 # Type of the kubernetes resource
metadata:                     
  name: book-details-service
  labels:                     # Labels that will be applied to this resource
    app: book-details-service
    env: dev
spec:                         
  type: NodePort              # The service will be exposed by opening a Port on each node and proxying it. 
  selector:
    app: book-details-service
    env: dev
  ports:                      # Forward incoming connections on port 8080 to the target port 8080
  - name: http
    port: 8080
    targetPort: 8080

---
# deployment
apiVersion: v1
kind: Pod
metadata:
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
    "consul.hashicorp.com/connect-service-upstreams": "book-service:9090,review-service:9095"
  name: book-details-service
  labels:
    app: book-details-service
    env: dev
spec:
  serviceAccountName: book-details-service-account
  containers:
  - name: book-details-service
    image: rnkoaa/book-details-service:latest
    env:
    - name: REVIEW_SERVICE_HOST 
      value: "local:127.0.0.1:9095"
    - name: BOOK_SERVICE_HOST 
      value: "local:127.0.0.1:9090"
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: book-details-service-config-volume
      mountPath: /application/config/application.yml
      subPath: application.yml
  volumes:
    - name: book-details-service-config-volume
      configMap: 
        name: book-details-service-config
