# helm install 
global:
  datacenter: dc1
ui:
  service:
    type: "NodePort"
connectInject:
  enabled: true

client:
  enabled: true
  grpc: true

server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 1
